// <auto-generated />
using Cellenza.Pinpon.Front;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cellenza.Pinpon.Front.Migrations
{
    [DbContext(typeof(PinponQueueContext))]
    [Migration("20180911152514_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("Cellenza.Pinpon.Front.Models.QueueInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConnectionString");

                    b.Property<string>("DisplayName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Subscription");

                    b.Property<string>("Topic");

                    b.HasKey("Id");

                    b.ToTable("QueueInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
